version: "3"

services:
  db:
    image: postgres:9.4
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=timed
      - POSTGRES_PASSWORD=timed

  frontend:
    image: adfinissygroup/timed-frontend:latest
    depends_on:
      - backend
    ports:
      - 4200:80

  backend:
    build: .
    ports:
      - 8000:80
    depends_on:
      - db
    environment:
      - DJANGO_DATABASE_HOST=db
      - DJANGO_DATABASE_PORT=5432
      - ENV=docker
      - STATIC_ROOT=/var/www/static

  keycloak:
    image: jboss/keycloak:10.0.1
    volumes:
      - ./dev-config/keycloak-config.json:/etc/keycloak/keycloak-config.json:ro
    depends_on:
      - db
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=db
      - DB_USER=timed
      - DB_DATABASE=timed
      - DB_PASSWORD=timed
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/etc/keycloak/keycloak-config.json

  proxy:
    image: nginx:1.17.10-alpine
    ports:
      - 80:80
    volumes:
      - ./dev-config/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  dbdata:
